no hardcoded node version

diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -13,8 +13,8 @@ echo "\n\n1.1 ensure nvm is in your current process\n\n"
   (echo 'Failed to ensure nvm is in this process.' && exit 1)
 
 echo "\n\n2. Install node\n"
-nvm install 10 || \
-  (echo 'Failed to install node version 10.' && exit 1)
+(cd $ROOT && nvm use) || \
+  (echo 'Failed to install target node version.' && exit 1)
 
 echo "\n\n3. Update npm to latest version\n\n"
 nvm install-latest-npm  || \
