Exercise setup script  (#3391)
* setup also builds server

* travis exercises setup

* outputting versions

* using nvm version 10.15.3

* added link to travis docs

diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -25,23 +25,27 @@ status() {
 
 status "1. Install nvm"
 curl -o- "https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh" | sh || \
-    fail "Failed to download nvm version $NVM_VERSION." 
+    fail "Failed to download nvm version $NVM_VERSION."
 
 status "1.1 ensure nvm is in your current process"
 . ~/.nvm/nvm.sh || source ~/.nvm/nvm.sh
 
 status "2. Install node"
-(cd $ROOT && nvm install && nvm use) || fail 'Failed to install target node version.' 
+(cd $ROOT && nvm install && nvm use) || fail 'Failed to install target node version.'
 
 status "3. Update npm to latest version"
 nvm install-latest-npm  || fail 'Failed to update npm to latest version.'
 
 status "4. Install dependencies"
-(cd $ROOT && npm ci) || fail 'Failed to install dependencies.' 
+(cd $ROOT && npm ci && npm --prefix=server ci) || fail 'Failed to install dependencies.'
 
 
 echo "$GRN$BLD\n\nSETUP COMPLETE\n$END"
-echo "Next, try the following:\n"
+echo "node --version"
+node --version
+echo "npm --version"
+npm --version
+echo "\nNext, try the following:\n"
 echo "- Setup git hooks: $CMD\`git config core.hooksPath tools/hooks\`$END"
 echo "- Serve the project: $CMD\`npm start\`$END"
 echo "- Run tests:"
