- Explicit choice in output path - minor revert: using [] - only adding path to profile it it doesn't exist.

diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -81,19 +81,17 @@ status "4.1. Install sigh dependencies"
 
 status "5. Install Bazel"
 
-status "5.1. Downloading install script"
-curl -O -L -s "$BAZEL_DEP" --output "$BAZEL_SCRIPT_NAME" || fail "Failed to download Bazel binary"
-ls
-status "5.2. Running install script"
-chmod +x $BAZEL_SCRIPT_NAME
-. $BAZEL_SCRIPT_NAME --user || source $BAZEL_SCRIPT_NAME --user || fail "Failed to install Bazel"
-echo 'export PATH="$PATH:$HOME/bin"'  >> ~/.profile || warn 'Failed to add "$HOME/bin" to $PATH'
-
-status "5.3. Clean up"
+status "5.1. Downloading and running install script"
+curl -L -s -O "$BAZEL_DEP" --output "$BAZEL_SCRIPT_NAME"
+chmod +x "$BAZEL_SCRIPT_NAME"
+"./$BAZEL_SCRIPT_NAME" --user || fail "Failed to install Bazel"
 rm "$BAZEL_SCRIPT_NAME"
 
-status "5.4. Set up the .bazelrc file"
-(cd $ROOT && echo "build --define=repo_root=$(pwd)" >> .bazelrc)
+status "5.2. Updating PATH"
+append_once 'export PATH="$PATH:$HOME/bin"' ~/.profile
+
+status "5.3. Set up the .bazelrc file"
+(cd $ROOT && append_once "build --define=repo_root=$(pwd)" .bazelrc)
 
 
 echo "$GRN$BLD\n\nSETUP COMPLETE\n$END"
