Fixes `tools/setup` for fresh Linux environments (#4506)
* pointed to nvm.sh directly

* fixing klint setup

* added /usr/local/google/home/alxrsngrtn/bin to path

* fix colors at end

diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -48,7 +48,7 @@ curl -L -s -o- "https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/in
 
 status "1.1 ensure nvm is in your current process"
 # shellcheck disable=SC1090
-. $NVM_DIR/nvm.sh || fail "Nvm load failed"
+. $HOME/.nvm/nvm.sh || fail "Nvm load failed"
 
 status "2. Install node"
 cd $ROOT && nvm install && nvm use || fail 'Failed to install target node version.'
@@ -65,22 +65,22 @@ status "4.1. Install useful optional dependencies"
 (cd $ROOT && npm install --no-save chokidar) || fail 'Failed to install optional dependencies.'
 
 status "5. Install ktlint"
-(cd $HOME/bin && curl -L -s -O https://github.com/pinterest/ktlint/releases/download/0.35.0/ktlint && cd -) || fail 'Failed to install ktlint'
+(mkdir -p $HOME/bin && cd $HOME/bin && curl -L -s -O https://github.com/pinterest/ktlint/releases/download/0.35.0/ktlint && cd -) || fail 'Failed to install ktlint'
 chmod a+x $HOME/bin/ktlint
+append_once 'export PATH="$HOME/bin:$PATH"' $HOME/.bashrc
 
-echo "$GRN$BLD\n\nSETUP COMPLETE\n$END"
-echo "node --version"
+echo -e "$GRN$BLD\n\nSETUP COMPLETE\n$END"
+echo -e "node --version"
 node --version
-echo "npm --version"
+echo -e "npm --version"
 npm --version
-echo "ktlint --version"
+echo -e "ktlint --version"
 ktlint --version
-echo "\nNext, try the following:\n"
-echo "- Setup git hooks: $CMD\`git config core.hooksPath tools/hooks\`$END"
-echo "- Serve the project: $CMD\`./tools/sigh devServer\`$END"
-echo "- Run tests:"
-echo "  - $CMD\`./tools/sigh test\`$END"
-echo "  - $CMD\`./tools/local-presubmit\`$END"
-
-echo "\nPlease source the updated environment variables:"
-echo "  - $CMD\`source ~/.profile\`$END"
+echo -e "\nNext, try the following:\n"
+echo -e "- Setup git hooks: $CMD\`git config core.hooksPath tools/hooks\`$END"
+echo -e "- Serve the project: $CMD\`./tools/sigh devServer\`$END"
+echo -e "- Run tests:"
+echo -e "  - $CMD\`./tools/sigh test\`$END"
+echo -e "  - $CMD\`./tools/local-presubmit\`$END"
+echo -e "\nPlease source the updated environment variables:"
+echo -e "  - $CMD\`source ~/.profile\`$END"
