OSX + Mac pre-requisites and Bazel install

diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -1,11 +1,8 @@
 #!/bin/sh
 
 ROOT=$(dirname $0)/..
-
 NVM_VERSION="v0.34.0"
-
-BAZEL_DEB="https://github.com/bazelbuild/bazel/releases/download/0.29.0/bazel_0.29.0-linux-x86_64.deb"
-BAZEL_PKG_NAME=$(basename "$BAZEL_DEB")
+BAZEL_VERSION="0.29.0"
 
 YLW="\033[33m"
 RED="\033[91m"
@@ -16,9 +13,12 @@ END="\033[0m"
 
 CMD="$BLD$YLW"
 
+warn() {
+    echo "$RED$BLD$1$END"
+}
 
 fail() {
-    echo "$RED$BLD$1$END"
+    warn $1
     exit 1
 }
 
@@ -26,8 +26,39 @@ status() {
     echo "$MAG$1$END"
 }
 
+# Detect Platform
+case $(uname | tr '[:upper:]' '[:lower:]') in
+  linux*)
+    OS_NAME=linux
+    BAZEL_DEP="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel_$BAZEL_VERSION-installer-linux-x86_64.sh"
+    ;;
+  darwin*)
+    OS_NAME=osx
+    BAZEL_DEP="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-darwin-x86_64.sh"
+    ;;
+  msys*)
+    OS_NAME=windows
+    BAZEL_DEP="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-windows-x86_64.exe"
+    ;;
+  *)
+    OS_NAME=notset
+    warn "Can't detect host OS"
+    ;;
+esac
+
+BAZEL_PKG_NAME=$(basename "$BAZEL_DEP")
+
+status "0. Pre-requisites"
+if [ "$OS_NAME" == "linux" ]; then
+  status "0.1 Installing pre-requisites for Bazel"
+  sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python3
+elif [ "$OS_NAME" == "osx" ]; then
+  status "0.1. Checking for Command Line Tools"
+  xcode-select --version || xcode-select --install || fail "Unable to install Command Line Tools"
+fi
+
 status "1. Install nvm"
-curl -o- "https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh" | sh || \
+curl -L -o- "https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh" | sh || \
     fail "Failed to download nvm version $NVM_VERSION."
 
 status "1.1 ensure nvm is in your current process"
@@ -45,10 +76,20 @@ status "4. Install dependencies"
 status "4.1. Install sigh dependencies"
 (cd $ROOT && ./tools/sigh install) || fail 'Failed to install sigh dependencies.'
 
-status "5. Install bazel"
-(wget "$BAZEL_DEB" && set -x && sudo dpkg -i $BAZEL_PKG_NAME)
+status "5. Install Bazel"
 
-status "5.1. Set up the .bazelrc file"
+status "5.1. Downloading install script"
+curl -O -L "$BAZEL_DEP" || fail "Failed to download Bazel binary"
+
+status "5.2. Running install script"
+(chmod +x $BAZEL_PKG_NAME && set -x && ( . $BAZEL_PKG_NAME --user || source $BAZEL_PKG_NAME --user)) \
+ || fail "Failed to install Bazel"
+echo 'export PATH="$PATH:$HOME/bin"'  >> ~/.profile || warn 'Failed to add "$HOME/bin" to $PATH'
+
+status "5.3. Clean up"
+rm "$BAZEL_PKG_NAME"
+
+status "5.4. Set up the .bazelrc file"
 (cd $ROOT && echo "build --define=repo_root=$(pwd)" >> .bazelrc)
 
 
@@ -57,6 +98,8 @@ echo "node --version"
 node --version
 echo "npm --version"
 npm --version
+echo "bazel --version"
+bazel --version
 echo "\nNext, try the following:\n"
 echo "- Setup git hooks: $CMD\`git config core.hooksPath tools/hooks\`$END"
 echo "- Serve the project: $CMD\`npm start\`$END"
